@startuml
'https://plantuml.com/class-diagram
class Solution43
{
app

+main()
}


class websiteGenerator{

+String siteName
+String author
+String path

+String createWebsite()
+String createJSFolder()
+String createCSSFolder()
+String createHTML()
}


app <--o WebsiteGenerator

@enduml