@startuml
'https://plantuml.com/class-diagram

class Solution45
{
+ void main
+ string output()


}

class ReadFile
{
+void readfile
++public ArrayList<String> getdata()
}

class WriteFile
{
+void writefile

+public int getModification()
}
@enduml